"""Model: the application's state and the rules that govern it.

Pure Python with no Flask, HTML or HTTP objects, so the rules hold no
matter how the state is displayed or changed, and can be tested directly.
The model never calls the language backend: the controller asks it to
`begin` an operation, runs the backend, and hands back the Result with
`finish` (or reports a crash with `fail`).
"""
import threading
from dataclasses import dataclass
from enum import Enum

from lambda_web.backend.contract import Artifact, Operation, Outcome, Result

MANUAL_NAME = "Manual input"
MAX_SOURCE_BYTES = 64 * 1024

EXECUTE_UNAVAILABLE = ("Execute runs code generated by Compile. It is "
                       "unavailable until compilation is implemented and "
                       "produces an artifact for this source.")


class Origin(Enum):
    UPLOAD = "upload"
    MANUAL = "manual"
    CANNED = "canned"


class StateError(Exception):
    """The requested change is not allowed in the current state."""


class ValidationError(Exception):
    """The source text was rejected; the session state is unchanged."""


@dataclass(frozen=True)
class Source:
    """An applied source: the text the tools operate on."""
    name: str
    origin: Origin
    text: str
    revision: int


@dataclass(frozen=True)
class ActionState:
    """Whether a tool action is available, and why not if it is not."""
    operation: Operation
    enabled: bool
    reason: str = ""


@dataclass(frozen=True)
class Job:
    """Everything the controller needs to run one operation."""
    operation: Operation
    revision: int
    text: str
    artifact: Artifact | None


@dataclass(frozen=True)
class Snapshot:
    """Read-only view of the session state, safe to hand to the view."""
    source: Source | None
    draft: str | None
    results: tuple[Result, ...]
    has_artifact: bool
    busy: Operation | None
    actions: tuple[ActionState, ...]

    @property
    def has_unapplied_edits(self) -> bool:
        return self.draft is not None

    @property
    def can_change_source(self) -> bool:
        """Upload, canned examples and manual input are allowed."""
        return self.busy is None and self.draft is None

    @property
    def can_apply_or_discard(self) -> bool:
        return self.busy is None and self.draft is not None

    def action(self, operation: Operation) -> ActionState:
        return next(a for a in self.actions if a.operation is operation)


def decode_upload(data: bytes) -> str:
    """Decode an uploaded file as UTF-8 (a leading BOM is dropped).

    Size is checked on the raw bytes first so an oversized file is
    rejected without decoding it.
    """
    if len(data) > MAX_SOURCE_BYTES:
        raise ValidationError(_too_large(len(data)))
    try:
        return data.decode("utf-8-sig")
    except UnicodeDecodeError as e:
        raise ValidationError(f"The file is not valid UTF-8 text "
                              f"(invalid byte at position {e.start}).") \
            from None


class Session:
    """State for one user. Every public method is atomic under a lock,
    and a rejected change raises before anything is modified."""

    def __init__(self):
        self._lock = threading.Lock()
        self._revision = 0
        self._source: Source | None = None
        self._draft: str | None = None
        self._draft_target: tuple[str, Origin] | None = None
        self._results: list[Result] = []
        self._artifact: Artifact | None = None
        self._busy: Operation | None = None

    # --- source changes -------------------------------------------------

    def load(self, name: str, text: str, origin: Origin) -> Snapshot:
        """Replace the applied source (upload or canned example)."""
        with self._lock:
            self._require_idle()
            self._require_no_draft("load new source")
            _validate(text)
            self._new_revision(name, origin, text)
            return self._snapshot()

    def load_upload(self, name: str, data: bytes) -> Snapshot:
        """Replace the applied source with an uploaded file's contents."""
        return self.load(name, decode_upload(data), Origin.UPLOAD)

    def open_manual(self) -> Snapshot:
        """Start a blank draft that becomes "Manual input" when applied."""
        with self._lock:
            self._require_idle()
            self._require_no_draft("open manual input")
            self._draft = ""
            self._draft_target = (MANUAL_NAME, Origin.MANUAL)
            return self._snapshot()

    def edit(self, text: str) -> Snapshot:
        """Replace the draft text. Edits the applied source if there is
        one; otherwise the draft becomes manual input. Drafts are not
        validated until they are applied."""
        with self._lock:
            self._require_idle()
            if self._draft is None:
                self._draft_target = (
                    (self._source.name, self._source.origin) if self._source
                    else (MANUAL_NAME, Origin.MANUAL))
            self._draft = text
            return self._snapshot()

    def apply(self) -> Snapshot:
        """Make the draft the applied source, as a new revision. A draft
        that fails validation stays in place for correction."""
        with self._lock:
            self._require_idle()
            if self._draft is None:
                raise StateError("There are no unapplied edits to apply.")
            _validate(self._draft)
            name, origin = self._draft_target
            self._new_revision(name, origin, self._draft)
            return self._snapshot()

    def discard(self) -> Snapshot:
        """Drop the draft; the applied source is unchanged."""
        with self._lock:
            self._require_idle()
            if self._draft is None:
                raise StateError("There are no unapplied edits to discard.")
            self._clear_draft()
            return self._snapshot()

    # --- operations -----------------------------------------------------

    def begin(self, operation: Operation) -> Job:
        """Mark `operation` as running and return what it should act on.
        Raises StateError with the reason if it is not available."""
        with self._lock:
            state = self._action_state(operation)
            if not state.enabled:
                raise StateError(state.reason)
            self._busy = operation
            return Job(operation, self._source.revision, self._source.text,
                       self._artifact)

    def finish(self, result: Result,
               artifact: Artifact | None = None) -> bool:
        """End the running operation with its result. A result for an
        older revision is ignored; returns whether it was stored. A
        Compile result replaces the artifact, so a failed compile
        invalidates the previous one."""
        with self._lock:
            if self._busy is None or result.operation is not self._busy:
                raise StateError("No matching operation is running.")
            self._busy = None
            if (self._source is None
                    or result.revision != self._source.revision):
                return False
            self._results.append(result)
            if result.operation is Operation.COMPILE:
                self._artifact = (artifact if artifact is not None
                                  and artifact.revision == result.revision
                                  else None)
            return True

    def fail(self, message: str) -> Result:
        """End the running operation after an unexpected error. Records a
        backend failure; the source is untouched and can be retried."""
        with self._lock:
            if self._busy is None:
                raise StateError("No operation is running.")
            result = Result(self._busy, self._source.revision,
                            Outcome.BACKEND_FAILURE, message)
            self._busy = None
            self._results.append(result)
            return result

    def snapshot(self) -> Snapshot:
        with self._lock:
            return self._snapshot()

    # --- internals (caller holds the lock) ------------------------------

    def _require_idle(self) -> None:
        if self._busy is not None:
            raise StateError(f"Wait for {self._busy.value} to finish.")

    def _require_no_draft(self, action: str) -> None:
        if self._draft is not None:
            raise StateError(
                f"Apply or discard your edits before you {action}.")

    def _action_state(self, operation: Operation) -> ActionState:
        if self._busy is not None:
            return ActionState(operation, False,
                               f"{self._busy.value} is running.")
        if self._draft is not None:
            return ActionState(operation, False,
                               "Apply or discard your edits first.")
        if self._source is None:
            return ActionState(operation, False,
                               "Load or enter source first.")
        if operation is Operation.EXECUTE and self._artifact is None:
            return ActionState(operation, False, EXECUTE_UNAVAILABLE)
        return ActionState(operation, True)

    def _new_revision(self, name: str, origin: Origin, text: str) -> None:
        self._revision += 1
        self._source = Source(name, origin, text, self._revision)
        self._results.clear()
        self._artifact = None
        self._clear_draft()

    def _clear_draft(self) -> None:
        self._draft = None
        self._draft_target = None

    def _snapshot(self) -> Snapshot:
        return Snapshot(self._source, self._draft, tuple(self._results),
                        self._artifact is not None, self._busy,
                        tuple(self._action_state(op) for op in Operation))


def _validate(text: str) -> None:
    if not text.strip():
        raise ValidationError("Source is empty.")
    size = len(text.encode("utf-8", errors="replace"))
    if size > MAX_SOURCE_BYTES:
        raise ValidationError(_too_large(size))


def _too_large(size: int) -> str:
    return (f"Source is {size:,} bytes; the limit is "
            f"{MAX_SOURCE_BYTES:,} bytes (64 KiB).")
