"""Controller action routes: dispatch to a substituted backend, busy
state, failures and retry. The view code is not involved or changed."""
import threading

import pytest

from lambda_web import create_app
from lambda_web.backend.contract import Operation, Outcome, Result
from lambda_web.backend.lambda_backend import LambdaBackend
from lambda_web.controller import examples
from tests.fakes import FakeBackend

FACT = examples.get("factorial").text


def body(resp):
    data = resp.get_json()
    return data["state"], data["error"]


def loaded(backend=None):
    backend = backend if backend is not None else FakeBackend()
    app = create_app(backend=backend)
    client = app.test_client()
    client.post("/api/source/canned/factorial")
    return app, client, backend


# --- dispatch (Test 5) ------------------------------------------------

@pytest.mark.parametrize("action, label", [
    ("lint", "Lint"), ("interpret", "Interpret"),
    ("typecheck", "Type-check"), ("compile", "Compile"),
])
def test_each_action_calls_its_backend_operation(action, label):
    _, client, backend = loaded()
    resp = client.post(f"/api/actions/{action}")
    state, error = body(resp)
    assert resp.status_code == 200 and error is None
    assert backend.calls == [(action, 1, FACT)]
    last = state["results"][-1]
    assert (last["operation"], last["revision"], last["outcome"]) == \
        (label, 1, "ok")
    assert state["busy"] is None


def test_execute_consumes_compiled_artifact_without_recompiling():
    _, client, backend = loaded(FakeBackend(artifact=True))
    state, _ = body(client.post("/api/actions/compile"))
    assert state["has_artifact"]
    client.post("/api/actions/execute")
    assert backend.calls == [("compile", 1, FACT), ("execute", 1, "generated")]


def test_execute_unavailable_without_artifact():
    _, client, backend = loaded()
    resp = client.post("/api/actions/execute")
    state, error = body(resp)
    assert resp.status_code == 409 and "generated by Compile" in \
        error["message"]
    assert backend.calls == [] and state["results"] == []


@pytest.mark.parametrize("setup, fragment", [
    (lambda c: None, "Load or enter source"),
    (lambda c: (c.post("/api/source/canned/factorial"),
                c.post("/api/source/edit", json={"text": "x"})),
     "Apply or discard"),
], ids=["no-source", "unapplied-edits"])
def test_actions_refused_without_applied_source(setup, fragment):
    backend = FakeBackend()
    client = create_app(backend=backend).test_client()
    setup(client)
    resp = client.post("/api/actions/lint")
    assert resp.status_code == 409 and fragment in body(resp)[1]["message"]
    assert backend.calls == []


def test_unknown_action_is_404():
    _, client, backend = loaded()
    resp = client.post("/api/actions/format")
    assert resp.status_code == 404 and backend.calls == []


def test_results_accumulate_then_clear_on_new_revision():
    _, client, _ = loaded()
    client.post("/api/actions/lint")
    state, _ = body(client.post("/api/actions/interpret"))
    assert [r["operation"] for r in state["results"]] == \
        ["Lint", "Interpret"]
    state, _ = body(client.post("/api/source/apply", json={"text": FACT}))
    assert state["results"] == [] and state["source"]["revision"] == 2


# --- real backend through HTTP (F5, F6, F7) ----------------------------

def test_real_lint_and_interpret_through_http():
    client = create_app(backend=LambdaBackend()).test_client()
    client.post("/api/source/canned/factorial")
    state, _ = body(client.post("/api/actions/lint"))
    assert state["results"][-1]["message"] == "No free variables found."
    state, _ = body(client.post("/api/actions/interpret"))
    assert state["results"][-1]["output"] == "D0Vint(arg1=3628800)"

    client.post("/api/source/apply", json={"text": 'D0Evar("x")'})
    state, _ = body(client.post("/api/actions/lint"))
    last = state["results"][-1]
    assert (last["outcome"], last["message"]) == \
        ("language error", "Undeclared variable(s): x")


def test_real_placeholders_never_report_success():
    client = create_app(backend=LambdaBackend()).test_client()
    client.post("/api/source/canned/factorial")
    for action in ("typecheck", "compile"):
        state, _ = body(client.post(f"/api/actions/{action}"))
        last = state["results"][-1]
        assert last["outcome"] == "not implemented" and not last["ok"]
    assert not state["has_artifact"]
    assert client.post("/api/actions/execute").status_code == 409


# --- busy state, failure and retry (Test 6, F10) -----------------------

def test_busy_blocks_other_requests_until_finished():
    gate = threading.Event()
    app, client, backend = loaded(FakeBackend(gate=gate))
    other = app.test_client()
    runner = threading.Thread(
        target=lambda: client.post("/api/actions/interpret"))
    runner.start()
    assert backend.started.wait(timeout=5)

    state, _ = body(other.get("/api/state"))
    assert state["busy"] == "Interpret"
    assert not any(a["enabled"] for a in state["actions"])
    assert not state["can_change_source"]
    for url, kwargs in [("/api/actions/lint", {}),
                        ("/api/source/canned/fibonacci", {}),
                        ("/api/source/edit", {"json": {"text": "x"}})]:
        resp = other.post(url, **kwargs)
        assert resp.status_code == 409
        assert "Interpret" in body(resp)[1]["message"]

    gate.set()
    runner.join(timeout=5)
    state, _ = body(other.get("/api/state"))
    assert state["busy"] is None and state["results"][-1]["ok"]
    assert all(a["enabled"] for a in state["actions"][:4])
    assert len(backend.calls) == 1


def test_backend_crash_is_recorded_and_retry_succeeds():
    _, client, _ = loaded(FakeBackend(crashes=1))
    state, _ = body(client.post("/api/actions/interpret"))
    failed = state["results"][-1]
    assert failed["outcome"] == "backend failure"
    assert "injected backend crash" in failed["message"]
    assert state["busy"] is None and state["source"]["text"] == FACT

    state, _ = body(client.post("/api/actions/interpret"))
    assert state["results"][-1]["ok"] and len(state["results"]) == 2


def test_wrong_result_from_backend_does_not_leave_page_busy():
    class WrongOperation(FakeBackend):
        def lint(self, source, revision):
            return Result(Operation.INTERPRET, revision, Outcome.OK, "?")

    _, client, _ = loaded(WrongOperation())
    state, _ = body(client.post("/api/actions/lint"))
    assert state["busy"] is None
    assert state["results"][-1]["outcome"] == "backend failure"
